# -*- coding: utf-8 -*-
"""01-eda-nyc-taxi-trip-analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hpgeFswENh93s6BPnjWxCtapiSKibMgI
"""

# New York City Taxi Trip Duration
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

# Set up asethetic plots
plt.style.use('default')
sns.set_palette("Set2")

print("NYC Taxi Trip Duration Analysis")
print("=" * 60)

# Load the dataset
try:
    df = pd.read_csv('/content/drive/MyDrive/EDA /New York City Taxi Trip Duration/Dataset/train.csv')
    print(f"✅ Dataset loaded successfully!")
    print(f"📊 We have {df.shape[0]:,} rows and {df.shape[1]} columns")
except FileNotFoundError:
    print("❌ Error: File Not Found!")

# =============================================================================
# STEP 1: WHAT'S IN OUR DATA?
# =============================================================================

print("\n" + "="*60)
print("STEP 1: UNDERSTANDING OUR DATA")
print("="*60)

"""
WHY WE DO WE HAVE TO UNDERSTAND THE DATA FIRST:
- Check how big our dataset is (like counting pages)
- Look at the first few rows (like reading the first paragraph)
- See what types of information we have (like checking if it's numbers or text)
"""

if not df.empty:
    print("\n📋 What columns (features) do we have?")
    for i, col in enumerate(df.columns, 1):
        print(f"{i}. {col}")

    print(f"\n📏 Dataset size: {len(df):,} taxi trips")

    print("\n👀 Let's peek at the first 3 trips:")
    print(df.head(3))

# =============================================================================
# STEP 2: IS OUR DATA CLEAN?
# =============================================================================

print("\n" + "="*60)
print("STEP 2: CHECKING IF OUR DATA IS CLEAN")
print("="*60)

"""
WHY WE CHECK FOR PROBLEMS:
- Bad data gives us wrong answers.
- Check for Missing values = empty spots where data should be
- Check for Duplicates = the same trip recorded twice (like double-counting)
"""

if not df.empty:
    # Check for missing data
    print("\n🔍 Looking for missing data...")
    missing_data = df.isnull().sum()
    if missing_data.sum() == 0:
        print("✅ Great! No missing data found")
    else:
        print("⚠️ Found some missing data:")
        print(missing_data[missing_data > 0])

    # Check for duplicates
    duplicates = df.duplicated().sum()
    print(f"\n🔍 Looking for duplicate trips...")
    if duplicates == 0:
        print("✅ Great! No duplicate trips found")
    else:
        print(f"⚠️ Found {duplicates} duplicate trips")

    # Basic statistics
    print("\n📊 Quick summary of our numbers:")
    print(f"• Shortest trip: {df['trip_duration'].min()} seconds")
    print(f"• Longest trip: {df['trip_duration'].max()} seconds")
    print(f"• Average trip: {df['trip_duration'].mean():.0f} seconds ({df['trip_duration'].mean()/60:.1f} minutes)")

# =============================================================================
# STEP 3: UNDERSTANDING TRIP TIMES
# =============================================================================

print("\n" + "="*60)
print("STEP 3: WHEN DO PEOPLE TAKE TAXIS?")
print("="*60)

"""
WHY WE LOOK AT TIME PATTERNS:
Taxis are busier at certain times throughout the day.
- Extract the hour from pickup time to see patterns
- Check if weekends are different from weekdays
- This helps us understand when demand is highest
"""

if not df.empty:
    # Convert pickup time to datetime (easier to work with)
    df['pickup_datetime'] = pd.to_datetime(df['pickup_datetime'])

    # Extract simple time features
    df['pickup_hour'] = df['pickup_datetime'].dt.hour
    df['is_weekend'] = df['pickup_datetime'].dt.dayofweek >= 5  # Saturday=5, Sunday=6

    print("\n🕐 What hours are taxis busiest?")
    hourly_trips = df['pickup_hour'].value_counts().sort_index()
    busiest_hour = hourly_trips.idxmax()
    print(f"Busiest hour: {busiest_hour}:00 with {hourly_trips[busiest_hour]:,} trips")

    print("\n🗓️ Weekend vs Weekday trips:")
    weekend_trips = df['is_weekend'].value_counts()
    print(f"Weekday trips: {weekend_trips[False]:,}")
    print(f"Weekend trips: {weekend_trips[True]:,}")

# =============================================================================
# STEP 4: HOW LONG ARE TAXI TRIPS?
# =============================================================================

print("\n" + "="*60)
print("STEP 4: UNDERSTANDING TRIP DURATIONS")
print("="*60)

"""
WHY WE ANALYZE TRIP DURATION:
Trip duration is what we want to predict.
- Look at typical trip lengths
- Find unusually short or long trips (outliers)
- See if trip length changes by time of day
"""

if not df.empty:
    print("\n⏱️ Trip Duration Facts:")
    print(f"• Average trip: {df['trip_duration'].mean()/60:.1f} minutes")
    print(f"• Typical trip (median): {df['trip_duration'].median()/60:.1f} minutes")
    print(f"• Shortest trip: {df['trip_duration'].min()} seconds")
    print(f"• Longest trip: {df['trip_duration'].max()/3600:.1f} hours")

    # Find unusual trips (simple method)
    very_short = df[df['trip_duration'] < 60].shape[0]  # Less than 1 minute
    very_long = df[df['trip_duration'] > 3600].shape[0]  # More than 1 hour

    print(f"\n🚨 Unusual trips:")
    print(f"• Very short trips (< 1 min): {very_short:,}")
    print(f"• Very long trips (> 1 hour): {very_long:,}")

    if very_short > 0 or very_long > 0:
        print("💡 These might be data errors or special cases to investigate")

# =============================================================================
# STEP 5: WHO RIDES IN TAXIS?
# =============================================================================

print("\n" + "="*60)
print("STEP 5: WHO RIDES IN TAXIS?")
print("="*60)

"""
WHY WE CHECK PASSENGER COUNTS:
Different group sizes might behave differently.
- Solo travelers might take quick trips
- Groups might make more stops or take longer trips
- Simple analysis helps us understand customer behavior
"""

if not df.empty:
    print("\n👥 How many passengers per trip?")
    passenger_counts = df['passenger_count'].value_counts().sort_index()
    for passengers, count in passenger_counts.items():
        percentage = (count / len(df)) * 100
        print(f"• {passengers} passenger(s): {count:,} trips ({percentage:.1f}%)")

    # Most common group size
    most_common = passenger_counts.idxmax()
    print(f"\n📈 Most common: {most_common} passenger(s)")

# =============================================================================
# STEP 6: SIMPLE VISUALIZATIONS
# =============================================================================

print("\n" + "="*60)
print("STEP 6: CREATING SIMPLE CHARTS")
print("="*60)

"""
WHY WE MAKE CHARTS:
Charts help us:
- See patterns that are hard to spot in tables
- Communicate findings to others easily
- Double-check our calculations visually
"""

if not df.empty:
    # Create simple, easy-to-understand charts
    fig, axes = plt.subplots(2, 2, figsize=(15, 10))
    fig.suptitle('NYC Taxi Analysis - Simple Charts', fontsize=16, fontweight='bold')

    # Chart 1: Trip duration histogram (focus on typical trips)
    typical_trips = df[df['trip_duration'] <= 3600]  # Only trips under 1 hour
    axes[0, 0].hist(typical_trips['trip_duration']/60, bins=30, color='skyblue', edgecolor='black')
    axes[0, 0].set_title('How Long Are Most Trips?')
    axes[0, 0].set_xlabel('Trip Duration (minutes)')
    axes[0, 0].set_ylabel('Number of Trips')

    # Chart 2: Trips by hour of day
    hourly_counts = df['pickup_hour'].value_counts().sort_index()
    axes[0, 1].plot(hourly_counts.index, hourly_counts.values, marker='o', linewidth=2, color='green')
    axes[0, 1].set_title('When Do People Take Taxis?')
    axes[0, 1].set_xlabel('Hour of Day')
    axes[0, 1].set_ylabel('Number of Trips')
    axes[0, 1].grid(True, alpha=0.3)

    # Chart 3: Passenger count bar chart
    passenger_counts = df['passenger_count'].value_counts().sort_index()
    axes[1, 0].bar(passenger_counts.index, passenger_counts.values, color='orange', edgecolor='black')
    axes[1, 0].set_title('How Many Passengers Per Trip?')
    axes[1, 0].set_xlabel('Number of Passengers')
    axes[1, 0].set_ylabel('Number of Trips')

    # Chart 4: Weekend vs Weekday trip duration
    weekend_data = [
        df[df['is_weekend'] == False]['trip_duration'].mean()/60,  # Weekday average
        df[df['is_weekend'] == True]['trip_duration'].mean()/60    # Weekend average
    ]
    axes[1, 1].bar(['Weekday', 'Weekend'], weekend_data, color=['lightcoral', 'lightblue'], edgecolor='black')
    axes[1, 1].set_title('Average Trip Duration: Weekday vs Weekend')
    axes[1, 1].set_ylabel('Average Duration (minutes)')

    plt.tight_layout()
    plt.show()

    print("📊 Charts created! Look for these patterns:")
    print("• Most trips are short (probably local transportation)")
    print("• Taxi demand varies throughout the day")
    print("• Most trips have 1-2 passengers")
    print("• Weekend vs weekday differences in trip length")

# =============================================================================
# STEP 7: SIMPLE PATTERNS AND INSIGHTS
# =============================================================================

print("\n" + "="*60)
print("STEP 7: WHAT PATTERNS DID WE FIND?")
print("="*60)

"""
WHY WE SUMMARIZE PATTERNS:
- It combines all our findings into simple insights
- It identifies the most important discoveries
- It suggests what to do next
"""

if not df.empty:
    print("\n🔍 KEY DISCOVERIES:")

    # Simple time pattern
    rush_hours = [7, 8, 9, 17, 18, 19]  # Morning and evening rush
    rush_hour_trips = df[df['pickup_hour'].isin(rush_hours)].shape[0]
    rush_hour_percent = (rush_hour_trips / len(df)) * 100
    print(f"• {rush_hour_percent:.1f}% of trips happen during rush hours (7-9 AM, 5-7 PM)")

    # Weekend vs weekday insight
    weekday_avg = df[df['is_weekend'] == False]['trip_duration'].mean()/60
    weekend_avg = df[df['is_weekend'] == True]['trip_duration'].mean()/60
    if weekend_avg > weekday_avg:
        print(f"• Weekend trips are longer ({weekend_avg:.1f} min vs {weekday_avg:.1f} min)")
    else:
        print(f"• Weekday trips are longer ({weekday_avg:.1f} min vs {weekend_avg:.1f} min)")

    # Passenger insight
    single_passenger_percent = (passenger_counts.get(1, 0) / len(df)) * 100
    print(f"• {single_passenger_percent:.1f}% of trips have just 1 passenger")

    # Data quality insight
    reasonable_trips = df[(df['trip_duration'] >= 60) & (df['trip_duration'] <= 3600)].shape[0]
    reasonable_percent = (reasonable_trips / len(df)) * 100
    print(f"• {reasonable_percent:.1f}% of trips have reasonable durations (1 min - 1 hour)")

